output   = "models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "odisha_dev"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = ""
  blacklist = ["migrations", "other"]
  sslmode = "disable"
  url = "postgres://postgres:@localhost:5432/odisha_dev?sslmode=disable"