// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Blocks           string
	Districts        string
	SchemaMigrations string
	Users            string
}{
	Blocks:           "blocks",
	Districts:        "districts",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
