// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// District is an object representing the database table.
type District struct {
	ID   int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *districtR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L districtL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DistrictColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

var DistrictTableColumns = struct {
	ID   string
	Name string
}{
	ID:   "districts.id",
	Name: "districts.name",
}

// Generated where

var DistrictWhere = struct {
	ID   whereHelperint
	Name whereHelperstring
}{
	ID:   whereHelperint{field: "\"districts\".\"id\""},
	Name: whereHelperstring{field: "\"districts\".\"name\""},
}

// DistrictRels is where relationship names are stored.
var DistrictRels = struct {
	Blocks string
}{
	Blocks: "Blocks",
}

// districtR is where relationships are stored.
type districtR struct {
	Blocks BlockSlice `boil:"Blocks" json:"Blocks" toml:"Blocks" yaml:"Blocks"`
}

// NewStruct creates a new relationship struct
func (*districtR) NewStruct() *districtR {
	return &districtR{}
}

func (r *districtR) GetBlocks() BlockSlice {
	if r == nil {
		return nil
	}
	return r.Blocks
}

// districtL is where Load methods for each relationship are stored.
type districtL struct{}

var (
	districtAllColumns            = []string{"id", "name"}
	districtColumnsWithoutDefault = []string{"name"}
	districtColumnsWithDefault    = []string{"id"}
	districtPrimaryKeyColumns     = []string{"id"}
	districtGeneratedColumns      = []string{}
)

type (
	// DistrictSlice is an alias for a slice of pointers to District.
	// This should almost always be used instead of []District.
	DistrictSlice []*District
	// DistrictHook is the signature for custom District hook methods
	DistrictHook func(context.Context, boil.ContextExecutor, *District) error

	districtQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	districtType                 = reflect.TypeOf(&District{})
	districtMapping              = queries.MakeStructMapping(districtType)
	districtPrimaryKeyMapping, _ = queries.BindMapping(districtType, districtMapping, districtPrimaryKeyColumns)
	districtInsertCacheMut       sync.RWMutex
	districtInsertCache          = make(map[string]insertCache)
	districtUpdateCacheMut       sync.RWMutex
	districtUpdateCache          = make(map[string]updateCache)
	districtUpsertCacheMut       sync.RWMutex
	districtUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var districtAfterSelectHooks []DistrictHook

var districtBeforeInsertHooks []DistrictHook
var districtAfterInsertHooks []DistrictHook

var districtBeforeUpdateHooks []DistrictHook
var districtAfterUpdateHooks []DistrictHook

var districtBeforeDeleteHooks []DistrictHook
var districtAfterDeleteHooks []DistrictHook

var districtBeforeUpsertHooks []DistrictHook
var districtAfterUpsertHooks []DistrictHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *District) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *District) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *District) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *District) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *District) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *District) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *District) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *District) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *District) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range districtAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDistrictHook registers your hook function for all future operations.
func AddDistrictHook(hookPoint boil.HookPoint, districtHook DistrictHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		districtAfterSelectHooks = append(districtAfterSelectHooks, districtHook)
	case boil.BeforeInsertHook:
		districtBeforeInsertHooks = append(districtBeforeInsertHooks, districtHook)
	case boil.AfterInsertHook:
		districtAfterInsertHooks = append(districtAfterInsertHooks, districtHook)
	case boil.BeforeUpdateHook:
		districtBeforeUpdateHooks = append(districtBeforeUpdateHooks, districtHook)
	case boil.AfterUpdateHook:
		districtAfterUpdateHooks = append(districtAfterUpdateHooks, districtHook)
	case boil.BeforeDeleteHook:
		districtBeforeDeleteHooks = append(districtBeforeDeleteHooks, districtHook)
	case boil.AfterDeleteHook:
		districtAfterDeleteHooks = append(districtAfterDeleteHooks, districtHook)
	case boil.BeforeUpsertHook:
		districtBeforeUpsertHooks = append(districtBeforeUpsertHooks, districtHook)
	case boil.AfterUpsertHook:
		districtAfterUpsertHooks = append(districtAfterUpsertHooks, districtHook)
	}
}

// OneG returns a single district record from the query using the global executor.
func (q districtQuery) OneG(ctx context.Context) (*District, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single district record from the query.
func (q districtQuery) One(ctx context.Context, exec boil.ContextExecutor) (*District, error) {
	o := &District{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for districts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all District records from the query using the global executor.
func (q districtQuery) AllG(ctx context.Context) (DistrictSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all District records from the query.
func (q districtQuery) All(ctx context.Context, exec boil.ContextExecutor) (DistrictSlice, error) {
	var o []*District

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to District slice")
	}

	if len(districtAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all District records in the query using the global executor
func (q districtQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all District records in the query.
func (q districtQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count districts rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q districtQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q districtQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if districts exists")
	}

	return count > 0, nil
}

// Blocks retrieves all the block's Blocks with an executor.
func (o *District) Blocks(mods ...qm.QueryMod) blockQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"blocks\".\"district_id\"=?", o.ID),
	)

	return Blocks(queryMods...)
}

// LoadBlocks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (districtL) LoadBlocks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDistrict interface{}, mods queries.Applicator) error {
	var slice []*District
	var object *District

	if singular {
		var ok bool
		object, ok = maybeDistrict.(*District)
		if !ok {
			object = new(District)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDistrict)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDistrict))
			}
		}
	} else {
		s, ok := maybeDistrict.(*[]*District)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDistrict)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDistrict))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &districtR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &districtR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`blocks`),
		qm.WhereIn(`blocks.district_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load blocks")
	}

	var resultSlice []*Block
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice blocks")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on blocks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for blocks")
	}

	if len(blockAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Blocks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &blockR{}
			}
			foreign.R.District = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.DistrictID) {
				local.R.Blocks = append(local.R.Blocks, foreign)
				if foreign.R == nil {
					foreign.R = &blockR{}
				}
				foreign.R.District = local
				break
			}
		}
	}

	return nil
}

// AddBlocksG adds the given related objects to the existing relationships
// of the district, optionally inserting them as new records.
// Appends related to o.R.Blocks.
// Sets related.R.District appropriately.
// Uses the global database handle.
func (o *District) AddBlocksG(ctx context.Context, insert bool, related ...*Block) error {
	return o.AddBlocks(ctx, boil.GetContextDB(), insert, related...)
}

// AddBlocks adds the given related objects to the existing relationships
// of the district, optionally inserting them as new records.
// Appends related to o.R.Blocks.
// Sets related.R.District appropriately.
func (o *District) AddBlocks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Block) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.DistrictID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"blocks\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"district_id"}),
				strmangle.WhereClause("\"", "\"", 2, blockPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.DistrictID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &districtR{
			Blocks: related,
		}
	} else {
		o.R.Blocks = append(o.R.Blocks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &blockR{
				District: o,
			}
		} else {
			rel.R.District = o
		}
	}
	return nil
}

// SetBlocksG removes all previously related items of the
// district replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.District's Blocks accordingly.
// Replaces o.R.Blocks with related.
// Sets related.R.District's Blocks accordingly.
// Uses the global database handle.
func (o *District) SetBlocksG(ctx context.Context, insert bool, related ...*Block) error {
	return o.SetBlocks(ctx, boil.GetContextDB(), insert, related...)
}

// SetBlocks removes all previously related items of the
// district replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.District's Blocks accordingly.
// Replaces o.R.Blocks with related.
// Sets related.R.District's Blocks accordingly.
func (o *District) SetBlocks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Block) error {
	query := "update \"blocks\" set \"district_id\" = null where \"district_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Blocks {
			queries.SetScanner(&rel.DistrictID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.District = nil
		}
		o.R.Blocks = nil
	}

	return o.AddBlocks(ctx, exec, insert, related...)
}

// RemoveBlocksG relationships from objects passed in.
// Removes related items from R.Blocks (uses pointer comparison, removal does not keep order)
// Sets related.R.District.
// Uses the global database handle.
func (o *District) RemoveBlocksG(ctx context.Context, related ...*Block) error {
	return o.RemoveBlocks(ctx, boil.GetContextDB(), related...)
}

// RemoveBlocks relationships from objects passed in.
// Removes related items from R.Blocks (uses pointer comparison, removal does not keep order)
// Sets related.R.District.
func (o *District) RemoveBlocks(ctx context.Context, exec boil.ContextExecutor, related ...*Block) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.DistrictID, nil)
		if rel.R != nil {
			rel.R.District = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("district_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Blocks {
			if rel != ri {
				continue
			}

			ln := len(o.R.Blocks)
			if ln > 1 && i < ln-1 {
				o.R.Blocks[i] = o.R.Blocks[ln-1]
			}
			o.R.Blocks = o.R.Blocks[:ln-1]
			break
		}
	}

	return nil
}

// Districts retrieves all the records using an executor.
func Districts(mods ...qm.QueryMod) districtQuery {
	mods = append(mods, qm.From("\"districts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"districts\".*"})
	}

	return districtQuery{q}
}

// FindDistrictG retrieves a single record by ID.
func FindDistrictG(ctx context.Context, iD int, selectCols ...string) (*District, error) {
	return FindDistrict(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindDistrict retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDistrict(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*District, error) {
	districtObj := &District{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"districts\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, districtObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from districts")
	}

	if err = districtObj.doAfterSelectHooks(ctx, exec); err != nil {
		return districtObj, err
	}

	return districtObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *District) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *District) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no districts provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(districtColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	districtInsertCacheMut.RLock()
	cache, cached := districtInsertCache[key]
	districtInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			districtAllColumns,
			districtColumnsWithDefault,
			districtColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(districtType, districtMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(districtType, districtMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"districts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"districts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into districts")
	}

	if !cached {
		districtInsertCacheMut.Lock()
		districtInsertCache[key] = cache
		districtInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single District record using the global executor.
// See Update for more documentation.
func (o *District) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the District.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *District) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	districtUpdateCacheMut.RLock()
	cache, cached := districtUpdateCache[key]
	districtUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			districtAllColumns,
			districtPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update districts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"districts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, districtPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(districtType, districtMapping, append(wl, districtPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update districts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for districts")
	}

	if !cached {
		districtUpdateCacheMut.Lock()
		districtUpdateCache[key] = cache
		districtUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q districtQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q districtQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for districts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for districts")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o DistrictSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DistrictSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), districtPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"districts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, districtPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in district slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all district")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *District) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *District) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no districts provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(districtColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	districtUpsertCacheMut.RLock()
	cache, cached := districtUpsertCache[key]
	districtUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			districtAllColumns,
			districtColumnsWithDefault,
			districtColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			districtAllColumns,
			districtPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert districts, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(districtPrimaryKeyColumns))
			copy(conflict, districtPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"districts\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(districtType, districtMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(districtType, districtMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert districts")
	}

	if !cached {
		districtUpsertCacheMut.Lock()
		districtUpsertCache[key] = cache
		districtUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single District record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *District) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single District record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *District) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no District provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), districtPrimaryKeyMapping)
	sql := "DELETE FROM \"districts\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from districts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for districts")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q districtQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q districtQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no districtQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from districts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for districts")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o DistrictSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DistrictSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(districtBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), districtPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"districts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, districtPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from district slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for districts")
	}

	if len(districtAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *District) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no District provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *District) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDistrict(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DistrictSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty DistrictSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DistrictSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DistrictSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), districtPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"districts\".* FROM \"districts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, districtPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DistrictSlice")
	}

	*o = slice

	return nil
}

// DistrictExistsG checks if the District row exists.
func DistrictExistsG(ctx context.Context, iD int) (bool, error) {
	return DistrictExists(ctx, boil.GetContextDB(), iD)
}

// DistrictExists checks if the District row exists.
func DistrictExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"districts\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if districts exists")
	}

	return exists, nil
}
